nginx:
  build: ./other/nginx/
  #image: dnmp_nginx:latest
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./www/:/var/www/html/:rw
    - ./conf/nginx/conf.d:/etc/nginx/conf.d/:ro
    - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./log/nginx/:/var/log/nginx/:rw
  links:
    - php-5.6:fpm-5.6

php-5.6:
  build: ./php/php-5.6/
  #image: dnmp_php-5.6:latest
  expose:
    - "9000"
  volumes:
    - ./www/:/var/www/html/:rw
    - ./conf/php-5.6/php.ini:/etc/php.ini:ro
    - ./conf/php-5.6/php-fpm.d/www.conf:/etc/php-fpm.d/www.conf:rw
    - ./log/php-fpm-5.6/:/var/log/php-fpm/:rw
  links:
    - mysql:mysql
  #  - redis:redis
    - memcached:memcached

mysql:
  build: ./other/mysql/
  #image: dnmp_mysql:latest
  ports:
    - "3306:3306"
  volumes:
    - ./conf/mysql/my.cnf:/etc/mysql/my.cnf:ro
    - ./mysql/:/var/lib/mysql/:rw
    - ./log/mysql/:/var/log/mysql/:rw
  environment:
    MYSQL_ROOT_PASSWORD: "123456"
memcached:
  build: ./other/memcached/
  #image: dnmp_redis:latest
  ports:
    - "11211:11211"

